# ESTE ARCHIVO .SQL ES PARA EJECUTAR LAS CONSULTAS VIEW DE LA BASE DE DATOS

# AQUI ESTAN TAMBIEN LA CREACION DE LAS VISTAS PARA QUE LAS PUEDAS VER


# CONSULTAS DE LAS VIEW

# 1. VIEW PARA CONSULTAR LOS EQUIPOS QUE FUERON ALQUILADOS POR LOS CLIENTES
SELECT * FROM rentmasterengine.vw_alquileres_de_equipos;

# 2. VIEW PARA CONSULTAR LOS EQUIPOS QUE FUERON ALQUILADOS Y NO ALQUILADOS
# POR LOS CLIENTE
SELECT * FROM rentmasterengine.vw_equipos_alquilados_y_no_alquilados;

# 3. VIEW PARA CONSULTAR LOS EQUIPOS QUE ESTEN EN ESTADO ALQUILADOS
SELECT * FROM rentmasterengine.vw_equipos_alquilados;

# 4. VIEW PARA CONSULTAR LOS EQUIPOS QUE ESTEN EN ESTADO DISPONIBLE
SELECT * FROM rentmasterengine.vw_equipos_disponibles;

# 5. VIEW PARA CONSULTAR LOS EQUIPOS QUE ESTEN EN ESTADO MANTENIMIENTO
SELECT * FROM rentmasterengine.vw_equipos_en_mantenimiento;

# 6. VIEW PARA CONSULTAR LA AUDITORIA DE LOS EQUIPOS A LOS QUE SE LES CAMBIO EL PRECIO
SELECT * FROM rentmasterengine.vw_auditoria_de_equipos;
/*

# ESTRUCTURA DE LAS VISTAS

*/